import { CustomStock } from "./types";

export const DSE_STOCKS: CustomStock[] = [
  { ticker: "OLYMPIC", companyName: "Olympic Industries Ltd." },
  { ticker: "MARICO", companyName: "Marico Bangladesh Ltd." },
  { ticker: "SQURPHARMA", companyName: "Square Pharmaceuticals Ltd." },
  { ticker: "BXPHARMA", companyName: "Beximco Pharmaceuticals Ltd." },
  { ticker: "BERGERPBL", companyName: "Berger Paints Bangladesh Ltd." },
  { ticker: "BATBC", companyName: "British American Tobacco Bangladesh Company Ltd." },
  { ticker: "RECKITTBEN", companyName: "Reckitt Benckiser (Bangladesh) Ltd." },
  { ticker: "GP", companyName: "Grameenphone Ltd." },
  { ticker: "ROBI", companyName: "Robi Axiata Ltd." },
  { ticker: "RENATA", companyName: "Renata Ltd." },
  { ticker: "LINDEBD", companyName: "Linde Bangladesh Ltd." },
  { ticker: "UNILEVERCL", companyName: "Unilever Consumer Care Ltd." },
  { ticker: "HEIDELBCEM", companyName: "Heidelberg Cement Bangladesh Ltd." },
  { ticker: "LAFSURMA", companyName: "LafargeHolcim Bangladesh Ltd." },
  { ticker: "BEXIMCO", companyName: "Bangladesh Export Import Company Ltd." },
  { ticker: "LHBL", companyName: "LafargeHolcim Bangladesh Ltd." },
  { ticker: "UPGDCL", companyName: "United Power Generation & Distribution Company Ltd." },
  { ticker: "TITASGAS", companyName: "Titas Gas Transmission & Distribution Company Ltd." },
  { ticker: "SUMITPOWER", companyName: "Summit Power Ltd." },
  { ticker: "MJLBD", companyName: "MJL Bangladesh Ltd." },
  { ticker: "JAMUNAOIL", companyName: "Jamuna Oil Company Ltd." },
  { ticker: "MPETROLEUM", companyName: "Meghna Petroleum Ltd." },
  { ticker: "PADMAOIL", companyName: "Padma Oil Company Ltd." },
  { ticker: "EBL", companyName: "Eastern Bank Ltd." },
  { ticker: "BRACBANK", companyName: "BRAC Bank Ltd." },
  { ticker: "CITYBANK", companyName: "The City Bank Ltd." },
  { ticker: "DUTCHBANGL", companyName: "Dutch-Bangla Bank Ltd." },
  { ticker: "ISLAMIBANK", companyName: "Islami Bank Bangladesh Ltd." },
  { ticker: "IDLC", companyName: "IDLC Finance Ltd." },
  { ticker: "LANKABAFIN", companyName: "LankaBangla Finance Ltd." },
  { ticker: "IPDC", companyName: "IPDC Finance Ltd." },
  { ticker: "ICB", companyName: "Investment Corporation of Bangladesh" },
  { ticker: "ACI", companyName: "ACI Ltd." },
  { ticker: "ACIMOTORS", companyName: "ACI Motors Ltd." },
  { ticker: "WALTONHIL", companyName: "Walton Hi-Tech Industries Ltd." },
  { ticker: "SINGERBD", companyName: "Singer Bangladesh Ltd." },
  { ticker: "RUNNERAUTO", companyName: "Runner Automobiles Ltd." },
  { ticker: "BSCCL", companyName: "Bangladesh Submarine Cable Company Ltd." },
  { ticker: "ORIONPHARM", companyName: "Orion Pharma Ltd." },
  { ticker: "IBP", companyName: "Ittefaq Bangladesh Ltd." },
  { ticker: "GPHISPAT", companyName: "GPH Ispat Ltd." },
  { ticker: "BSRMLTD", companyName: "BSRM Ltd." },
  { ticker: "BSRMSTEEL", companyName: "BSRM Steels Ltd." },
  { ticker: "KDSALTD", companyName: "KDS Accessories Ltd." },
  { ticker: "MAMUNAGRO", companyName: "Mamun Agro Products Ltd." },
  { ticker: "BDTHAI", companyName: "BD Thai Aluminium Ltd." },
  { ticker: "CONFIDCEM", companyName: "Confidence Cement Ltd." },
  { ticker: "PREMIERCEM", companyName: "Premier Cement Mills Ltd." },
  { ticker: "MEGHNACEM", companyName: "Meghna Cement Mills Ltd." },
  { ticker: "RAKCERAMIC", companyName: "RAK Ceramics (Bangladesh) Ltd." },
  { ticker: "GOLDENSON", companyName: "Golden Son Ltd." },
  { ticker: "SAIFPOWER", companyName: "Saif Powertec Ltd." },
  { ticker: "NAVANACNG", companyName: "Navana CNG Ltd." },
  { ticker: "IFADAUTOS", companyName: "IFAD Autos Ltd." },
  { ticker: "AFTABAUTO", companyName: "Aftab Automobiles Ltd." },
  { ticker: "BEACONPHAR", companyName: "Beacon Pharmaceuticals Ltd." },
  { ticker: "IBNSINA", companyName: "The Ibn Sina Pharmaceutical Industry Ltd." },
  { ticker: "PHARMAID", companyName: "Pharma Aids Ltd." },
  { ticker: "CENTRALPHL", companyName: "Central Pharmaceuticals Ltd." },
  { ticker: "SILCOPHL", companyName: "Silco Pharmaceuticals Ltd." },
  { ticker: "INDO-BANGLA", companyName: "Indo-Bangla Pharmaceuticals Ltd." },
  { ticker: "ACTIVEFINE", companyName: "Active Fine Chemicals Ltd." },
  { ticker: "KEYACOSMET", companyName: "Keya Cosmetics Ltd." },
  { ticker: "KOHINOOR", companyName: "Kohinoor Chemical Company (Bangladesh) Ltd." },
  { ticker: "SAPORTL", companyName: "Summit Alliance Port Ltd." },
  { ticker: "MALEKSPIN", companyName: "Malek Spinning Mills Ltd." },
  { ticker: "SQUARETEXT", companyName: "Square Textiles Ltd." },
  { ticker: "ENVOYTEX", companyName: "Envoy Textiles Ltd." },
  { ticker: "PARAMOUNT", companyName: "Paramount Textile Ltd." },
  { ticker: "ARGONDENIM", companyName: "Argon Denims Ltd." },
  { ticker: "HWAWELLTEX", companyName: "Hwa Well Textiles (BD) Ltd." },
  { ticker: "MLDYEING", companyName: "M.L. Dyeing Ltd." },
  { ticker: "VFSTHREAD", companyName: "V.F.S. Thread Dyeing Ltd." },
  { ticker: "KATTALI", companyName: "Kattali Textile Ltd." },
  { ticker: "QUEENSOUTH", companyName: "Queen South Textile Mills Ltd." },
  { ticker: "SHEPHERD", companyName: "Shepherd Industries Ltd." },
  { ticker: "SIMTEX", companyName: "Simtex Industries Ltd." },
  { ticker: "TALLUSPIN", companyName: "Tallu Spinning Mills Ltd." },
  { ticker: "MITHUNKNIT", companyName: "Mithun Knitting and Dyeing (CEPZ) Ltd." },
  { ticker: "AL-HAJTEX", companyName: "Al-Haj Textile Mills Ltd." },
  { ticker: "DULAMIA", companyName: "Dulamia Cotton Spinning Mills Ltd." },
  { ticker: "MONNOFABR", companyName: "Monno Fabrics Ltd." },
  { ticker: "STYLECRAFT", companyName: "Stylecraft Ltd." },
  { ticker: "ANLIMAYARN", companyName: "Anlima Yarn Dyeing Ltd." },
  { ticker: "SONARGAON", companyName: "Sonargaon Textiles Ltd." },
  { ticker: "PRIME-TEX", companyName: "Prime Textile Spinning Mills Ltd." },
  { ticker: "SAIHAMTEX", companyName: "Saiham Textile Mills Ltd." },
  { ticker: "SAIHAMCOT", companyName: "Saiham Cotton Mills Ltd." },
  { ticker: "MATINSPINN", companyName: "Matin Spinning Mills Ltd." },
  { ticker: "MAKSONSPIN", companyName: "Maksons Spinning Mills Ltd." },
  { ticker: "METROSPIN", companyName: "Metro Spinning Ltd." },
  { ticker: "RNSPIN", companyName: "R.N. Spinning Mills Ltd." },
  { ticker: "ZAHEENSPIN", companyName: "Zaheen Spinning Mills Ltd." },
  { ticker: "EVENCE", companyName: "Evence Textiles Ltd." },
  { ticker: "PACIFICDEN", companyName: "Pacific Denims Ltd." },
  { ticker: "ACME", companyName: "The ACME Laboratories Ltd." },
  { ticker: "SILVAPHL", companyName: "Silva Pharmaceuticals Ltd." },
  { ticker: "GENEXIL", companyName: "Genex Infosys Ltd." },
  { ticker: "ADNTEL", companyName: "ADN Telecom Ltd." },
  { ticker: "AAMRANET", companyName: "aamra networks ltd." },
  { ticker: "AAMRATECH", companyName: "aamra technologies ltd." },
  { ticker: "DAFODILCOM", companyName: "Daffodil Computers Ltd." },
  { ticker: "BDCOM", companyName: "BDCOM Online Ltd." },
  { ticker: "ITC", companyName: "Information Technology Consultants Ltd." },
  { ticker: "EGEN", companyName: "eGeneration Ltd." },
];
